# Generated by Django 2.1.5 on 2019-01-20 07:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190120_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='author_email',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[blog.models.validate_author_email]),
        ),
    ]
